package:
  name: poretools
  version: "0.6.0"
source:
  fn: poretools-0.6.0.tar.gz
  url: https://pypi.python.org/packages/57/28/b680b8515e4d02b583211c2287fd9e49700dc6cfa0b2b6d6a11f54d0b8a1/poretools-0.6.0.tar.gz
  md5: 8bc38dd5a08f9b34ec4ef19a6805f6fd

requirements:
  build:
    - python
    - setuptools
    - h5py >=2.2.0
    - matplotlib
    - seaborn
    - pandas
    - python
    - setuptools
    - h5py >=2.2.0
    - matplotlib
    - seaborn
    - pandas

  run:
    - python
    - h5py >=2.2.0
    - matplotlib
    - seaborn
    - pandas

build:
  skip: True # [not py27 or osx]

test:
  imports:
    - poretools
    - poretools.scripts

  commands:
    - poretools --help


about:
  home: http://poretools.readthedocs.org/
  summary: "poretools: a toolkit for working with nanopore sequencing data from Oxford Nanopore"
  license: GNU General Public License (GPL)

