{% set version = "2.1.1" %}

package:
  name: khmer
  version: {{ version }}

source:
  fn: khmer-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/k/khmer/khmer-{{ version }}.tar.gz
  sha256: a709606910bb8679bd8525e9d2bf6d1421996272e343b54cc18090feb2fdbe24

build:
  number: 0

requirements:
  build:
    - gcc  # [not osx]
    - llvm  # [osx]
    - python
    - setuptools
    - screed >=1.0
    - bz2file
    - pytest-runner

  run:
    - libgcc  # [not osx]
    - python
    - screed >=1.0
    - bz2file

test:
  # Python imports
  imports:
    - khmer
    - khmer.tests
    - oxli

about:
  home: https://khmer.readthedocs.io/
  license: BSD License
  summary: 'khmer k-mer counting library'
  license_family: BSD
