package:
  name: links
  version: "1.8.3"

source:
  fn: links_v1-8-3.tar.gz
  url: http://www.bcgsc.ca/platform/bioinfo/software/links/releases/1.8.3/links_v1-8-3.tar.gz
  md5: feb3f14ee3442f298c82d88251175cf3

  patches:
    - links.patch

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - perl-threaded

  run:
    - perl-threaded
    - perl-bloomfilter

test:
  commands:
    - LINKS   | grep 'Usage' > /dev/null

about:
  summary: Long Interval Nucleotide K-mer Scaffolder
  home: http://www.bcgsc.ca/platform/bioinfo/software/links
  license: GPL
  license_file: LINKS-readme.txt
