package:
  name: rnalien
<<<<<<< HEAD
  version: '1.2.2'

source:
  fn: 1.2.2.tar.gz
  url: https://github.com/eggzilla/RNAlien/archive/1.2.2.tar.gz

build:
  number: 0
  skip: 

requirements:
  build:
    - stack >=stack-1.1.2
    - gmp

  run:
    - viennarna >=2.1.9
    - rnaz >=2.1
    - locarna >=1.8.7
    - infernal >=1.1.1
    - gmp
=======
  version: '1.2.5'

source:
  fn: 1.2.5.tar.gz
  url: https://github.com/eggzilla/RNAlien/archive/1.2.5.tar.gz

build:
  number: 0
  skip: True  #  [osx]

requirements:
  build:
    - stack >=1.2.0
    - perl-threaded
    - gmp
    - zlib

  run:
    - viennarna >=2.2.10
    - rnaz >=2.1
    - locarna >=1.8.11
    - infernal >=1.1.1
    - gmp
    - perl-threaded
    - libgcc
>>>>>>> upstream/master

test:
  commands:
    - RNAlien -?

about:
  home: http://rna.tbi.univie.ac.at/rnalien/tool
  license: GPL-3
  summary: A tool for unsupervised construction of RNA family models
