package:
  name: extract_vcf
  version: "0.5"

source:
  fn: extract_vcf-0.5.tar.gz
  url: https://pypi.python.org/packages/source/e/extract_vcf/extract_vcf-0.5.tar.gz
  md5: 444c9214a110cc108474b09a1d40313b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - extract_vcf = extract_vcf:main
    #
    # Would create an entry point called extract_vcf that calls extract_vcf.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - configobj

  run:
    - python
    - configobj

test:
  # Python imports
  imports:
    - extract_vcf

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/moonso/extract_vcf
  license: BSD License
  summary: 'Tool to extract information from vcf file.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
