{% set name = "nanopolish" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  string: "ncurses{{CONDA_NCURSES}}_{{PKG_BUILDNUM}}"

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/jts/nanopolish/archive/v{{ version }}.tar.gz
  sha256: 098a7548a417b68494270eb9d4e063b51bf4e48895743284f61f8e3c908031fa
  patches:
    - nanopolish.patch

requirements:
  build:
  - gcc
  - fast5 ==0.6.3.p1
  - htslib
  - hdf5 1.8.18|1.8.18.*
  - eigen
  - ncurses {{CONDA_NCURSES}}*

  run:
  - libgcc
  - python
  - hdf5 1.8.18|1.8.18.*
  - biopython
  - bwa
  - eigen
  - ncurses {{CONDA_NCURSES}}*

test:
  commands:
    - nanopolish --help
    - nanopolish --version

about:
  home: https://github.com/jts/nanopolish
  license: MIT
  license_file: LICENSE
  summary: 'Signal-level algorithms for MinION data.'
  
