about:
  home: https://igdiscover.readthedocs.io/
  license: 'MIT'
  summary: 'Analyze antibody repertoires and discover new V genes'
package:
  name: igdiscover
  version: "0.3"
source:
  fn: igdiscover-0.3.tar.gz
  url: https://pypi.python.org/packages/ba/ff/bc398601c92d05bf502bcd3f49897b20cd3a0fe41cde0f17c8f073222ad4/igdiscover-0.3.tar.gz
  md5: 132e771db3e168018a613c0900b560d9
requirements:
  run:
    - python
    - sqt >=0.6.3
    - pandas >=0.16.2
    - numpy
    - matplotlib
    - snakemake
    - cutadapt
    - seaborn >=0.6.0
    - scipy ==0.16.1
    - pyyaml
    - muscle
    - pear
    - flash
    - igblast ==1.4.0
    - vsearch ==1.9.7
    - fastqc
  build:
    - python
    - sqt >=0.6.3
    - pandas >=0.16.2
    - numpy
    - matplotlib
    - snakemake
    - cutadapt
    - seaborn >=0.6.0
    - scipy ==0.16.1
    - pyyaml
build:
  number: 1
  skip: True  # [py27]
  script: python3 setup.py install
test:
  commands:
    - igdiscover --help > /dev/null
