{% set name = "libgenome" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  fn: {{ name|lower }}_{{ version }}.zip
  url: https://github.com/druvus/mauve_snapshot/raw/master/mauve-code-4736-libGenome-trunk.zip
  md5: ebe9c42963c09626821cb4e30398f3d2

requirements:
  build:
  - gcc  # [not osx]
  - llvm  # [osx]
  - autoconf 
  - automake
  - perl
  - libtool

  run:
  - libgcc  # [not osx]

test:
  commands:
    - ls $PREFIX/lib/libGenome-1.3.la | grep libGenome
    - test -e $PREFIX/lib/libGenome-1.3.la
about:
  home: http://darlinglab.org/mauve/
  license: GPLv2
  summary: libGenome header files.
