{% set name = "emboss" %}
{% set version = "6.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 2

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: ftp://emboss.open-bio.org/pub/EMBOSS/old/6.5.0/EMBOSS-{{ version }}.tar.gz
  md5: 6a2cb3f93d5e9415c74ab0f6b1ede5f0

requirements:
  build:
   - gcc  # [linux]
   - llvm  # [osx]
   - python
   - zlib
  run:
   - zlib
   - libgcc  # [not osx]
about:
  home: http://emboss.open-bio.org/
  license: GPL
  summary: The European Molecular Biology Open Software Suite 

test:
  commands:
    # test a few tools 
    -  needle --help
    -  transeq --help
    -  sixpack --help
    -  seqret --help
