package:
  name: cwltool
  version: '1.0.20161005195021'

source:
  fn: cwltool-1.0.20161005195021.tar.gz
  url: https://pypi.python.org/packages/c3/d9/ed2876f6bb9fab744694cea8cf4803552e93ec0fdef5df0d4e3d5a751706/cwltool-1.0.20161005195021.tar.gz
  md5: 1906ba9713975461c9477b73d2b998ae

build:
  number: 0
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools
    - requests
    - ruamel.yaml >=0.12.4
    - rdflib
    - rdflib-jsonld
    - shellescape
    - cwltest
    - schema-salad ==1.18.20161005190847
    - typing >=3.5.2

  run:
    - python
    - setuptools
    - requests
    - ruamel.yaml >=0.12.4
    - rdflib
    - rdflib-jsonld
    - shellescape
    - cwltest
    - schema-salad ==1.18.20161005190847
    - typing >=3.5.2

test:
  imports:
    - cwltool
  commands:
    - cwltool --help

about:
  home: https://github.com/common-workflow-language/cwltool
  license: Apache License 2.0
  summary: Common Workflow Language reference implementation
