{% set name = "unicycler" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  # Build will be skipped for all platforms due to GCC 
  # being out of date.  Offline builds only for now

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/rrwick/Unicycler/archive/v{{ version }}.tar.gz
  sha256: e25e7423119aec5e574324c403f8ae36d93c0ce1497853d42c1a49a2a924a1f4
#  patches:
#    - Makefile.patch [linux]
#    - misc.py.patch

requirements:
  build:
  - python
  - setuptools
  - gcc

  run:
  - python
  - libgcc
  - spades >=3.6.2
  - pilon
  - openjdk
  - bowtie2
  - samtools >=1.0
  - blast
  - freebayes
  - racon
  - miniasm

test:
  commands:
    - unicycler -h
    - unicycler_align -h
    - unicycler_check -h
    - unicycler_polish -h

about:
  home: https://github.com/rrwick/Unicycler
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Hybrid assembly pipeline for bacterial genomes'
