{% set name = "jemalloc" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: "https://github.com/jemalloc/jemalloc/releases/download/3.6.0/jemalloc-3.6.0.tar.bz2"
  sha256: e16c2159dd3c81ca2dc3b5c9ef0d43e1f2f45b04548f42db12e7c12d7bdf84fe

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc  # [not osx]
    - llvm # [osx]
  run:
    - libgcc # [not osx]
    - perl-threaded

test:
  commands:
    - pprof --version

about:
  home: https://github.com/jemalloc/jemalloc
  license: BSD
  summary: 'jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.'
