package:
  name: bioconductor-rcas
  version: 1.0.1
source:
  fn: RCAS_1.0.1.tar.gz
  url: https://bioconductor.org/packages/release/bioc/src/contrib/RCAS_1.0.1.tar.gz
  md5: 32208a2335c5c9d6745fb3cb55ff9550
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - 'bioconductor-genomation >=1.5.5'
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-org.hs.eg.db
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-topgo
    - r
    - r-data.table
    - 'r-dt >=0.2'
    - 'r-knitr >=1.12.3'
    - r-motifrg,
    - 'r-plotly >=4.5.2'
    - 'r-rmarkdown >=0.9.5'
    - r-stats
    - pandoc >=1.12.3
  run:
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - 'bioconductor-genomation >=1.5.5'
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-org.hs.eg.db
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-topgo
    - r
    - r-data.table
    - 'r-dt >=0.2'
    - 'r-knitr >=1.12.3'
    - r-motifrg,
    - 'r-plotly >=4.5.2'
    - 'r-rmarkdown >=0.9.5'
    - r-stats
    - pandoc >=1.12.3

test:
  commands:
    - $R -e "library('RCAS')"

about:
  home: https://bioconductor.org/packages/release/bioc/html/RCAS.html
  license: Artistic-2.0Artistic-2.0
  summary: 'RNA Centric Annotation System (RCAS) is an automated system
  that provides dynamic annotations for custom input files
  that contain transcriptomic targe regions.'
