{% set name = "roprofile.py" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True # [not py27]

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/cimendes/roProfile/archive/e9bc33adb9cd78ec9800c7a8e72828140ff68511.tar.gz
  md5: a0e1f9f48b08f38a60291ae81602f75b

  patches:
    - roprofile.patch

requirements:
  build:

  run:
  - python
  - biopython >=1.66
  - matplotlib >=1.5.2
  - mpld3 >=0.2
  - pandas >=0.15.0
test:
  commands:
    - roProfile.py --version

about:
  home: https://github.com/cimendes/roProfile
  license: GPLv3
  summary: 'Generation of pan-genome profile files using Roary output.'
 
