{% set name = "roprofile.py" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True # [not py27]

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/cimendes/roProfile/archive/1.4.0.tar.gz
  md5: 87822e4f8914ad0245f266c1afa25cf8

  patches:
    - roprofile.patch

requirements:
  build:

  run:
  - python
  - biopython >=1.66
  - matplotlib >=1.5.2
  - mpld3 >=0.2 
  - pandas >=0.15.0
test:
  commands:
    - roprofile.py --version

about:
  home: https://github.com/isovic/graphmap
  license: GPLv3
  summary: 'Generation of pan-genome profile files using Roary output.'
