{% set name = "orfm" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/wwood/OrfM/archive/v0.5.3.tar.gz
  md5: 4310068135499f3f5e02cd1a29c59710

requirements:
  build:
    - gcc  # [not osx]
    - llvm  # [osx]

  run:
    - libgcc   # [not osx]

test:
  commands:
    - orfm -h

about:
  home: https://github.com/wwood/OrfM
  license: GPL3
  license_file: LICENSE.txt
  summary: 'OrfM is a simple and not slow ORF caller'
  
