package:
  name: seqprep
  version: 1.2

source:
  fn: v1.2.tar.gz
  url: https://github.com/jstjohn/SeqPrep/archive/v1.2.tar.gz
  md5: 7501064b519b6e17b2a6c39ec0a03b2d

  patches:
    - cflags.patch

build:
  number: 0

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - zlib

  run:
    - zlib
    - libgcc    # [not osx]

test:
  commands:
    - SeqPrep  2>&1 | grep Usage > /dev/null

about:
  home: https://github.com/jstjohn/SeqPrep
  summary: Tool for stripping adaptors and/or merging paired reads with overlap into single reads.
  license: MIT

