package:
  name: bioconductor-motifrg
  version: 1.18.0
source:
  fn: motifRG_1.18.0.tar.gz
  url: https://bioarchive.galaxyproject.org/motifRG_1.18.0.tar.gz
  md5: b955881a77ea0fd57df6e02bf212d440
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biostrings >=2.26'
    - bioconductor-bsgenome
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-iranges
    - bioconductor-seqlogo
    - bioconductor-xvector
    - r
  run:
    - 'bioconductor-biostrings >=2.26'
    - bioconductor-bsgenome
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-iranges
    - bioconductor-seqlogo
    - bioconductor-xvector
    - r
test:
  commands:
    - '$R -e "library(''motifRG'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/motifRG.html
  license: Artistic-2.0
  summary: 'Tools for discriminative motif discovery using regression methods'
