{% set version = "1.1" %}

package:
  name: spacegraphcats
  version: {{ version }}

source:
  url: https://github.com/spacegraphcats/spacegraphcats/archive/v{{ version }}.tar.gz
  sha256: f900a07e8ea7d2c3b0ddd99eb07a6351c749d201cf281defbd8b5aa60b6341b0

build:
  entry_points:
    - spacegraphcats = spacegraphcats.__main__:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools >=38.6.0

  run:
    - python >= 3.5
    - khmer >= 3.0a2
    - bcalm >= 2

test:
  imports:
    - spacegraphcats

  commands:
    - spacegraphcats --help

about:
  home: https://github.com/spacegraphcats/spacegraphcats
  license: BSD License
  summary: 'Analyze and use graph structure in large compact De Bruijn graphs'
  license_family: BSD
  dev_url: https://github.com/spacegraphcats/spacegraphcats
