package:
  name: bioconductor-rgraphviz
  version: 2.18.0
source:
  fn: Rgraphviz_2.18.0.tar.gz
  url: https://bioarchive.galaxyproject.org/Rgraphviz_2.18.0.tar.gz
  md5: 63068b63cabe69c315c1b2f60eb7b197
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-graph
    - r
    - gcc
    - graphviz

  run:
    - bioconductor-graph
    - r
    - libgcc
    - graphviz

test:
  commands:
    - '$R -e "library(''Rgraphviz'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/Rgraphviz.html
  license: EPL
  summary: 'Interfaces R with the AT and T graphviz library for plotting R graph objects
    from the graph package.'
