package:
  name: bioconductor-rgraphviz
  version: 2.16.0
source:
  fn: Rgraphviz_2.16.0.tar.gz
  url: https://bioarchive.galaxyproject.org/Rgraphviz_2.16.0.tar.gz
  md5: 7cc78d664091137d805709970cb00879
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-graph
    - r
    - gcc  # [not osx]
    - llvm  # [osx]
  run:
    - bioconductor-graph
    - r
    - libgcc  # [not osx]
test:
  commands:
    - '$R -e "library(''Rgraphviz'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/Rgraphviz.html
  license: EPL
  summary: 'Interfaces R with the AT and T graphviz library for plotting R graph objects
    from the graph package.'
