package:
  name: pandaseq
  version: "2.10"

build:
  number: 1

source:
  fn: pandaseq_v2.10.tar.gz
  url: https://github.com/neufeld/pandaseq/archive/v2.10.tar.gz
  md5: 5b5b04c9b693a999f10a9c9bd643f068

requirements:
  build:
  - perl-threaded
  - gcc  # [not osx]
  - llvm  # [osx]
  - autoconf
  - automake
  - zlib
  - pkg-config
  - libtool
  - bzip2
  
  run:
  - libgcc  # [not osx]

test:
  commands:
    - pandaseq -h 2>&1 | grep 'Usage'

about:
  home: https://github.com/neufeld/pandaseq
  license: GPL3
  license_file: COPYING
  summary: PANDASEQ is a program to align Illumina reads, optionally with PCR primers embedded in the sequence, and reconstruct an overlapping sequence.
