{% set version = "1.2.3.2" %}

package:
  name: clark
  version: {{ version }}

build:
  number: 0

source:
  fn: CLARK_{{ version }}.tar.gz
  url: http://clark.cs.ucr.edu/Download/CLARKV{{ version }}.tar.gz
  sha256: e41637273281d9a554c4afb7ab8e3e77534db085097f30e1210932b90ae867de

requirements:
  build:
  - gcc  # [not osx]
  - llvm  # [osx]

  run:
  - libgcc  # [not osx]

test:
  commands:
    - CLARK --help 
    - CLARK-l --help 
    - CLARK-S --help 

about:
  home: http://clark.cs.ucr.edu/
  license: GPL3
  license_file: LICENSE_GNU_GPL.txt
  summary: Fast, accurate and versatile k-mer based classification system
