package:
  name: canu
  version: "1.0"

build:
  # skip: True # [not py27]
  number: 0

source:
  fn: canu-v1.0.tar.gz
  url: https://github.com/marbl/canu/archive/v1.0.tar.gz
  md5: 4f5b3e4ff2f0e3d894885ddc82fc1a2d

requirements:
  build:
  - gcc
  - perl-threaded

  run:
  - libgcc
  - perl-threaded

test:
  commands:
    - canu | grep usage > /dev/null

about:
  home: https://github.com/marbl/canu
  license: Custom
  license_file: README.licenses
  summary: A single molecule sequence assembler for genomes large and small

